name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pcalimache
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64\
            --tag pcalimache/portfolio:latest \
            --push .
